import type { MatchableConversionFactor } from '../utils/conversionFactorMatching';

export const pilotFactorCoverage = ['Alberta', 'British Columbia', 'Ontario'] as const;
export const pilotUnsupportedElectricityProvinces = ['Quebec', 'Saskatchewan'] as const;

export const pilotConversionFactors: MatchableConversionFactor[] = [
  {
    id: 'factor-electricity-ab',
    name: 'Electricity - Alberta - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.53,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'Alberta',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    id: 'factor-electricity-bc',
    name: 'Electricity - British Columbia - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.02,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'British Columbia',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    id: 'factor-electricity-on',
    name: 'Electricity - Ontario - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.12,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'Ontario',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    id: 'factor-diesel',
    name: 'Diesel - 2026',
    type: 'EMISSION',
    activityType: 'DIESEL',
    inputUnit: 'L',
    factorValue: 2.68,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-natural-gas',
    name: 'Natural Gas - 2026',
    type: 'EMISSION',
    activityType: 'NATURAL_GAS',
    inputUnit: 'm3',
    factorValue: 1.89,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-flight',
    name: 'Business Travel - Flight - 2026',
    type: 'EMISSION',
    activityType: 'AIR_TRAVEL',
    inputUnit: 'km',
    factorValue: 0.16,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-hotel',
    name: 'Hotel Stay - 2026',
    type: 'EMISSION',
    activityType: 'HOTEL',
    inputUnit: 'nights',
    factorValue: 18,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'pilot-ground-transport-canada-2025',
    name: 'Ground Transport - Canada - 2025',
    type: 'EMISSION',
    activityType: 'GROUND_TRANSPORT',
    inputUnit: 'km',
    factorValue: 0.2,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdiction: 'Canada - National',
    jurisdictionRegion: 'Canada - National',
    sourceAuthority: 'CarbonLite',
    sourceYear: 2025,
    confidenceLevel: 'Pilot Estimate',
    verificationStatus: 'Internal Review Required',
    isSystemDefault: true,
    isDefault: true,
    defaultScope: 'SCOPE_3',
    scope: 'SCOPE_3',
    verified: false,
  },
];

export const pilotExpectedEmissions = {
  scope1KgCO2e: 457,
  scope2KgCO2e: 265,
  scope3KgCO2e: 210,
  totalKgCO2e: 932,
};
