import type { MatchableConversionFactor } from '../utils/conversionFactorMatching';

export const pilotFactorCoverage = ['Alberta', 'British Columbia', 'Ontario'] as const;
export const pilotUnsupportedElectricityProvinces = ['Quebec', 'Saskatchewan'] as const;

const pilotDefaultMetadata = {
  sourceAuthority: 'CarbonLite',
  sourceName: 'CarbonLite Pilot Default Factors',
  sourceDocument: 'CarbonLite Pilot Default Factor Set v0.1',
  sourceUrl: '/methodology/default-factors',
  factorSet: 'PILOT_DEFAULT_V0_1',
  factorStatus: 'ACTIVE',
  confidence: 'PILOT_ESTIMATE',
  confidenceLevel: 'Pilot Estimate',
  verificationStatus: 'Internal Review Required',
  lastReviewedAt: '2026-01-01T00:00:00.000Z',
};

const ecccElectricityMetadata = {
  type: 'EMISSION',
  activityType: 'ELECTRICITY',
  inputUnit: 'kWh',
  resultUnit: 'kgCO2e',
  jurisdictionCountry: 'Canada',
  sourceAuthority: 'Environment and Climate Change Canada',
  sourceName: 'ECCC electricity consumption intensity reference',
  sourceDocument: 'ECCC electricity consumption intensity reference',
  sourceUrl: '/methodology/eccc-electricity-reference',
  factorStatus: 'ACTIVE',
  confidence: 'HIGH',
  confidenceLevel: 'HIGH',
  verificationStatus: 'ACTIVE',
  boundary: 'Purchased electricity consumption intensity.',
  notes: 'Official reference factor stored separately from CarbonLite pilot defaults.',
  isSystemDefault: true,
  isDefault: false,
  verified: true,
};

export const ecccReferenceElectricityFactors: MatchableConversionFactor[] = [
  {
    ...ecccElectricityMetadata,
    id: 'eccc-electricity-ab-2025',
    name: 'Electricity - Alberta - 2025 Reference',
    factorValue: 0.49,
    jurisdictionRegion: 'Alberta',
    sourceYear: 2025,
    effectiveYear: 2025,
    factorVersion: 'ECCC_REFERENCE_2025',
    factorSet: 'ECCC_REFERENCE_2025',
  },
  {
    ...ecccElectricityMetadata,
    id: 'eccc-electricity-bc-2025',
    name: 'Electricity - British Columbia - 2025 Reference',
    factorValue: 0.015,
    jurisdictionRegion: 'British Columbia',
    sourceYear: 2025,
    effectiveYear: 2025,
    factorVersion: 'ECCC_REFERENCE_2025',
    factorSet: 'ECCC_REFERENCE_2025',
  },
  {
    ...ecccElectricityMetadata,
    id: 'eccc-electricity-on-2025',
    name: 'Electricity - Ontario - 2025 Reference',
    factorValue: 0.038,
    jurisdictionRegion: 'Ontario',
    sourceYear: 2025,
    effectiveYear: 2025,
    factorVersion: 'ECCC_REFERENCE_2025',
    factorSet: 'ECCC_REFERENCE_2025',
  },
  {
    ...ecccElectricityMetadata,
    id: 'eccc-electricity-ab-2026',
    name: 'Electricity - Alberta - 2026 Reference',
    factorValue: 0.438,
    jurisdictionRegion: 'Alberta',
    sourceYear: 2026,
    effectiveYear: 2026,
    factorVersion: 'ECCC_REFERENCE_2026',
    factorSet: 'ECCC_REFERENCE_2026',
  },
  {
    ...ecccElectricityMetadata,
    id: 'eccc-electricity-bc-2026',
    name: 'Electricity - British Columbia - 2026 Reference',
    factorValue: 0.018,
    jurisdictionRegion: 'British Columbia',
    sourceYear: 2026,
    effectiveYear: 2026,
    factorVersion: 'ECCC_REFERENCE_2026',
    factorSet: 'ECCC_REFERENCE_2026',
  },
  {
    ...ecccElectricityMetadata,
    id: 'eccc-electricity-on-2026',
    name: 'Electricity - Ontario - 2026 Reference',
    factorValue: 0.059,
    jurisdictionRegion: 'Ontario',
    sourceYear: 2026,
    effectiveYear: 2026,
    factorVersion: 'ECCC_REFERENCE_2026',
    factorSet: 'ECCC_REFERENCE_2026',
  },
];

export const pilotConversionFactors: MatchableConversionFactor[] = [
  {
    ...pilotDefaultMetadata,
    id: 'factor-electricity-ab',
    name: 'Electricity - Alberta - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.53,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'Alberta',
    sourceYear: 2026,
    effectiveYear: 2026,
    boundary: 'Purchased electricity consumption intensity for pilot workflow validation.',
    notes: 'Preserved pilot default factor used by CarbonLite Pilot Demo v0.1 golden dataset.',
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'factor-electricity-bc',
    name: 'Electricity - British Columbia - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.02,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'British Columbia',
    sourceYear: 2026,
    effectiveYear: 2026,
    boundary: 'Purchased electricity consumption intensity for pilot workflow validation.',
    notes: 'Preserved pilot default factor used by CarbonLite Pilot Demo v0.1 golden dataset.',
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'factor-electricity-on',
    name: 'Electricity - Ontario - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.12,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'Ontario',
    sourceYear: 2026,
    effectiveYear: 2026,
    boundary: 'Purchased electricity consumption intensity for pilot workflow validation.',
    notes: 'Preserved pilot default factor used by CarbonLite Pilot Demo v0.1 golden dataset.',
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'factor-diesel',
    name: 'Diesel - 2026',
    type: 'EMISSION',
    activityType: 'DIESEL',
    inputUnit: 'L',
    factorValue: 2.68,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    effectiveYear: 2026,
    boundary: 'Mobile combustion diesel fuel volume.',
    notes: 'Display unit standardized to L; pilot value preserved for golden totals.',
    isSystemDefault: true,
    isDefault: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'factor-natural-gas',
    name: 'Natural Gas - 2026',
    type: 'EMISSION',
    activityType: 'NATURAL_GAS',
    inputUnit: 'm3',
    factorValue: 1.89,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    effectiveYear: 2026,
    boundary: 'Stationary combustion natural gas volume in cubic metres.',
    notes: 'Natural gas m3 factor does not match GJ usage; GJ requires a distinct factor.',
    isSystemDefault: true,
    isDefault: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'factor-flight',
    name: 'Business Travel - Flight - 2026',
    type: 'EMISSION',
    activityType: 'AIR_TRAVEL',
    inputUnit: 'km',
    factorValue: 0.16,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    effectiveYear: 2026,
    factorStatus: 'REVIEW_RECOMMENDED',
    boundary: 'Selected Scope 3 business air travel distance.',
    notes: 'Pilot-stage Scope 3 factor. Consultant review recommended before formal reporting.',
    isSystemDefault: true,
    isDefault: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'factor-hotel',
    name: 'Business Travel - Accommodation - 2026',
    type: 'EMISSION',
    activityType: 'HOTEL',
    inputUnit: 'nights',
    factorValue: 18,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    effectiveYear: 2026,
    factorStatus: 'REVIEW_RECOMMENDED',
    boundary: 'Selected Scope 3 business travel accommodation nights.',
    notes: 'User-facing label is Business Travel - Accommodation; internal activity type remains HOTEL.',
    isSystemDefault: true,
    isDefault: true,
  },
  {
    ...pilotDefaultMetadata,
    id: 'pilot-ground-transport-canada-2025',
    name: 'Ground Transport - Canada - 2025',
    type: 'EMISSION',
    activityType: 'GROUND_TRANSPORT',
    inputUnit: 'km',
    factorValue: 0.2,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdiction: 'Canada - National',
    jurisdictionRegion: 'Canada - National',
    sourceYear: 2025,
    effectiveYear: 2025,
    factorStatus: 'GENERIC_ESTIMATE',
    confidence: 'LOW',
    boundary: 'Generic distance-based Scope 3 ground transport estimate.',
    notes: 'Generic estimate for workflow review. Professional review recommended before formal reporting.',
    isSystemDefault: true,
    isDefault: true,
    defaultScope: 'SCOPE_3',
    scope: 'SCOPE_3',
    verified: false,
  },
  ...ecccReferenceElectricityFactors,
];

export const pilotExpectedEmissions = {
  scope1KgCO2e: 457,
  scope2KgCO2e: 265,
  scope3KgCO2e: 210,
  totalKgCO2e: 932,
};
