import type { MatchableConversionFactor } from '../utils/conversionFactorMatching';

export const pilotFactorCoverage = ['Alberta', 'British Columbia', 'Ontario'] as const;
export const pilotUnsupportedElectricityProvinces = ['Quebec', 'Saskatchewan'] as const;

export const pilotConversionFactors: MatchableConversionFactor[] = [
  {
    id: 'factor-electricity-ab',
    name: 'Electricity - Alberta - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.52,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'Alberta',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    id: 'factor-electricity-bc',
    name: 'Electricity - British Columbia - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.012,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'British Columbia',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    id: 'factor-electricity-on',
    name: 'Electricity - Ontario - 2026',
    type: 'EMISSION',
    activityType: 'ELECTRICITY',
    inputUnit: 'kWh',
    factorValue: 0.03,
    resultUnit: 'kgCO2e',
    jurisdictionCountry: 'Canada',
    jurisdictionRegion: 'Ontario',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
    verified: true,
  },
  {
    id: 'factor-diesel',
    name: 'Diesel - 2026',
    type: 'EMISSION',
    activityType: 'DIESEL',
    inputUnit: 'L',
    factorValue: 2.68,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-natural-gas',
    name: 'Natural Gas - 2026',
    type: 'EMISSION',
    activityType: 'NATURAL_GAS',
    inputUnit: 'm3',
    factorValue: 1.89,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-flight',
    name: 'Business Travel - Flight - 2026',
    type: 'EMISSION',
    activityType: 'AIR_TRAVEL',
    inputUnit: 'km',
    factorValue: 0.16,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-hotel',
    name: 'Hotel Stay - 2026',
    type: 'EMISSION',
    activityType: 'HOTEL',
    inputUnit: 'nights',
    factorValue: 18,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
  {
    id: 'factor-ground-transport',
    name: 'Ground Transport - 2026',
    type: 'EMISSION',
    activityType: 'GROUND_TRANSPORT',
    inputUnit: 'km',
    factorValue: 0.22,
    resultUnit: 'kgCO2e',
    sourceYear: 2026,
    isSystemDefault: true,
    isDefault: true,
  },
];

export const pilotExpectedEmissions = {
  scope1KgCO2e: 457,
  scope2KgCO2e: 260,
  scope3KgCO2e: 212,
  totalKgCO2e: 929,
};
